server:
  listenAddress: "localhost"
  port: 3000
  debug: true
dbSync:
  host: "cdbsync-testnet.mydomain.com"
  port: 5432
  user: "cdbsync"
  database: "cdbsync"
  maxConnections: 10
  ssl: true
network: "testnet"
tokenRegistryUrl: "https://metadata.cardano-testnet.iohkdev.io"
